# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/anchor_generator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import grid_anchor_generator_pb2 as protos_dot_grid__anchor__generator__pb2
from protos import ssd_anchor_generator_pb2 as protos_dot_ssd__anchor__generator__pb2
from protos import multiscale_anchor_generator_pb2 as protos_dot_multiscale__anchor__generator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dprotos/anchor_generator.proto\x12\x06protos\x1a\"protos/grid_anchor_generator.proto\x1a!protos/ssd_anchor_generator.proto\x1a(protos/multiscale_anchor_generator.proto\"\xef\x01\n\x0f\x41nchorGenerator\x12<\n\x15grid_anchor_generator\x18\x01 \x01(\x0b\x32\x1b.protos.GridAnchorGeneratorH\x00\x12:\n\x14ssd_anchor_generator\x18\x02 \x01(\x0b\x32\x1a.protos.SsdAnchorGeneratorH\x00\x12H\n\x1bmultiscale_anchor_generator\x18\x03 \x01(\x0b\x32!.protos.MultiscaleAnchorGeneratorH\x00\x42\x18\n\x16\x61nchor_generator_oneof')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.anchor_generator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANCHORGENERATOR._serialized_start=155
  _ANCHORGENERATOR._serialized_end=394
# @@protoc_insertion_point(module_scope)
