# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/model.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import faster_rcnn_pb2 as protos_dot_faster__rcnn__pb2
from protos import ssd_pb2 as protos_dot_ssd__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/model.proto\x12\x06protos\x1a\x18protos/faster_rcnn.proto\x1a\x10protos/ssd.proto\"`\n\x0e\x44\x65tectionModel\x12)\n\x0b\x66\x61ster_rcnn\x18\x01 \x01(\x0b\x32\x12.protos.FasterRcnnH\x00\x12\x1a\n\x03ssd\x18\x02 \x01(\x0b\x32\x0b.protos.SsdH\x00\x42\x07\n\x05model')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.model_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DETECTIONMODEL._serialized_start=74
  _DETECTIONMODEL._serialized_end=170
# @@protoc_insertion_point(module_scope)
