# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/string_int_label_map.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protos/string_int_label_map.proto\x12\x06protos\"G\n\x15StringIntLabelMapItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\"@\n\x11StringIntLabelMap\x12+\n\x04item\x18\x01 \x03(\x0b\x32\x1d.protos.StringIntLabelMapItem')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.string_int_label_map_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRINGINTLABELMAPITEM._serialized_start=45
  _STRINGINTLABELMAPITEM._serialized_end=116
  _STRINGINTLABELMAP._serialized_start=118
  _STRINGINTLABELMAP._serialized_end=182
# @@protoc_insertion_point(module_scope)
