# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import eval_pb2 as protos_dot_eval__pb2
from protos import graph_rewriter_pb2 as protos_dot_graph__rewriter__pb2
from protos import input_reader_pb2 as protos_dot_input__reader__pb2
from protos import model_pb2 as protos_dot_model__pb2
from protos import train_pb2 as protos_dot_train__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/pipeline.proto\x12\x06protos\x1a\x11protos/eval.proto\x1a\x1bprotos/graph_rewriter.proto\x1a\x19protos/input_reader.proto\x1a\x12protos/model.proto\x1a\x12protos/train.proto\"\xaf\x02\n\x17TrainEvalPipelineConfig\x12%\n\x05model\x18\x01 \x01(\x0b\x32\x16.protos.DetectionModel\x12)\n\x0ctrain_config\x18\x02 \x01(\x0b\x32\x13.protos.TrainConfig\x12/\n\x12train_input_reader\x18\x03 \x01(\x0b\x32\x13.protos.InputReader\x12\'\n\x0b\x65val_config\x18\x04 \x01(\x0b\x32\x12.protos.EvalConfig\x12.\n\x11\x65val_input_reader\x18\x05 \x01(\x0b\x32\x13.protos.InputReader\x12-\n\x0egraph_rewriter\x18\x06 \x01(\x0b\x32\x15.protos.GraphRewriter*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.pipeline_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAINEVALPIPELINECONFIG._serialized_start=149
  _TRAINEVALPIPELINECONFIG._serialized_end=452
# @@protoc_insertion_point(module_scope)
