# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/region_similarity_calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)protos/region_similarity_calculator.proto\x12\x06protos\"\xd2\x01\n\x1aRegionSimilarityCalculator\x12=\n\x16neg_sq_dist_similarity\x18\x01 \x01(\x0b\x32\x1b.protos.NegSqDistSimilarityH\x00\x12/\n\x0eiou_similarity\x18\x02 \x01(\x0b\x32\x15.protos.IouSimilarityH\x00\x12/\n\x0eioa_similarity\x18\x03 \x01(\x0b\x32\x15.protos.IoaSimilarityH\x00\x42\x13\n\x11region_similarity\"\x15\n\x13NegSqDistSimilarity\"\x0f\n\rIouSimilarity\"\x0f\n\rIoaSimilarity')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.region_similarity_calculator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGIONSIMILARITYCALCULATOR._serialized_start=54
  _REGIONSIMILARITYCALCULATOR._serialized_end=264
  _NEGSQDISTSIMILARITY._serialized_start=266
  _NEGSQDISTSIMILARITY._serialized_end=287
  _IOUSIMILARITY._serialized_start=289
  _IOUSIMILARITY._serialized_end=304
  _IOASIMILARITY._serialized_start=306
  _IOASIMILARITY._serialized_end=321
# @@protoc_insertion_point(module_scope)
